# Generated by Django 5.1.6 on 2025-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='read_books',
            field=models.ManyToManyField(blank=True, related_name='read_by_users', to='books.book'),
        ),
    ]
