# Generated by Django 5.1.6 on 2025-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_genre_alter_book_cover_image_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_genres',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, to='books.genre'),
        ),
    ]
